package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;
import Modelo.Estudiante;
import java.util.ArrayList;

/**
 * Ventana de Mantenimiento de Estudiantes: Añade los estudiantes y los registra
 * @author Daniel Somarribas - b57072
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    //Define el controlador y el ArrayList del objeto Estudiante
    Controlador_FRM_MantenimientoEstudiantes controladorEstudiantes;
    ArrayList <Estudiante> arrayEstudiantes;
    
    /**
     * Crea el Frame FRM_MantenimientoEstudiantes
     */
    
    //Método Constructor: Define el Frame y su controlador
    public FRM_MantenimientoEstudiantes() 
    {
        initComponents();
        setVisible(false);
        setResizable(false);
        controladorEstudiantes = new Controlador_FRM_MantenimientoEstudiantes(this);
        GUI_BotonesEstudiantes.agregarEventosGUI(controladorEstudiantes);
        GUI_InformacionEstudiante.agregarEventosGUI(controladorEstudiantes);        
        this.jb_MostrarTodos.addActionListener(controladorEstudiantes);
    }

    //Set del ArrayList de Estudiantes
    public void setArrayEstudiantes()
    {
        arrayEstudiantes = controladorEstudiantes.getArrayEstudiantes();
    }
    
    //Devuelve el ArrayList de Estudiantes
    public ArrayList <Estudiante> getArrayEstudiantes()
    {
        setArrayEstudiantes();
        return arrayEstudiantes;
    }
    
    /**
     * Métodos del Frame
     * Estos métodos interactúan con lo que se muestra
     * (ej: Llenar campos vacíos)
     */
    
    /**
     * Devuelve el String escrito en todos los campos
     * @return the Estudiantes information String
     */
    public String[] getInformacionEscrita()
    {
        return this.GUI_InformacionEstudiante.getInformacionEscrita();
    }
    
    public void configInic()
    {
        GUI_InformacionEstudiante.configInic();
        GUI_BotonesEstudiantes.configInic();
    }
    
    public void configBusc()
    {
        GUI_InformacionEstudiante.configEnab();
        GUI_BotonesEstudiantes.configBusc();
    }
    
    public void configAgreg()
    {
        GUI_InformacionEstudiante.configEnab();
        GUI_BotonesEstudiantes.configAgreg();
    }
    
    /**
     * Devuelve el String en el campo de Cédula
     * @return the cedula
     */
    public String getCedulaEscrita()
    {
        return this.GUI_InformacionEstudiante.getCedulaEscrita();
    }
    
    //Pide al panel llenar los campos (con la información buscada)
    public void fillFields(String cedula, String nombre, String direccion)
    {
       GUI_InformacionEstudiante.fillFields(cedula, nombre, direccion);
    }
    
    //Pide al panel limpiar todos los campos
    public void clearFields()
    {
       GUI_InformacionEstudiante.clearFields();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUI_InformacionEstudiante = new Vista.GUI_InformacionEstudiante();
        GUI_BotonesEstudiantes = new Vista.GUI_BotonesEstudiantes();
        jb_MostrarTodos = new javax.swing.JButton();

        setTitle("Mantenimiento de Estudiantes");

        jb_MostrarTodos.setText("Mostrar Todos");
        jb_MostrarTodos.setActionCommand("Todos");
        jb_MostrarTodos.setPreferredSize(new java.awt.Dimension(72, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUI_InformacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GUI_BotonesEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_MostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI_InformacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUI_BotonesEstudiantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jb_MostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesEstudiantes GUI_BotonesEstudiantes;
    private Vista.GUI_InformacionEstudiante GUI_InformacionEstudiante;
    private javax.swing.JButton jb_MostrarTodos;
    // End of variables declaration//GEN-END:variables
}