/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;

/**
 *
 * @author estudiante
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    Controlador_FRM_MantenimientoEstudiantes controladorEstudiantes;
    /**
     * Creates new form FRM_MantenimientoEstudiantes
     */
    public FRM_MantenimientoEstudiantes() 
    {
        initComponents();
        setVisible(false);
        setResizable(false);
        controladorEstudiantes = new Controlador_FRM_MantenimientoEstudiantes(this);
        GUI_BotonesEstudiantes.agregarEventosGUI(controladorEstudiantes);
        GUI_InformacionEstudiante.agregarEventosGUI(controladorEstudiantes);        
        this.jb_MostrarTodos.addActionListener(controladorEstudiantes);
    }

    public String[] getInformacionEscrita()
    {
        return this.GUI_InformacionEstudiante.getInformacionEscrita();
    }
    
    public String getCedulaEscrita()
    {
        return this.GUI_InformacionEstudiante.getCedulaEscrita();
    }
    
    public void fillFields(String cedula, String nombre, String direccion)
    {
       GUI_InformacionEstudiante.fillFields(cedula, nombre, direccion);
    }
    
    public void clearFields()
    {
       GUI_InformacionEstudiante.clearFields();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUI_InformacionEstudiante = new Vista.GUI_InformacionEstudiante();
        GUI_BotonesEstudiantes = new Vista.GUI_BotonesEstudiantes();
        jb_MostrarTodos = new javax.swing.JButton();

        setTitle("Mantenimiento de Estudiantes");

        jb_MostrarTodos.setText("Mostrar Todos");
        jb_MostrarTodos.setActionCommand("Todos");
        jb_MostrarTodos.setPreferredSize(new java.awt.Dimension(72, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUI_InformacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GUI_BotonesEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_MostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI_InformacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUI_BotonesEstudiantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jb_MostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesEstudiantes GUI_BotonesEstudiantes;
    private Vista.GUI_InformacionEstudiante GUI_InformacionEstudiante;
    private javax.swing.JButton jb_MostrarTodos;
    // End of variables declaration//GEN-END:variables
}
