package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;
import Modelo.Curso;
import java.util.ArrayList;

/**
 * Ventana de Mantenimiento de Cursos: Añade los cursos y los registra
 * @author daniel
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame 
{
    //Define el controlador y el ArrayList del objeto Curso
    Controlador_FRM_MantenimientoCursos controladorCursos;
    ArrayList <Curso> arrayCursos;
        
    /**
     * Crea el Frame FRM_MantenimientoCursos
     */
    
    //Método Constructor: Define el Frame y su controlador
    public FRM_MantenimientoCursos() 
    {
        initComponents();
        setVisible(false);
        setResizable(false);
        controladorCursos = new Controlador_FRM_MantenimientoCursos(this);
        GUI_BotonesCursos.agregarEventosGUI(controladorCursos);
        GUI_InformacionCursos.agregarEventosGUI(controladorCursos);
    }
    
    //Set del ArrayList de Cursos
    public void setArrayCursos()
    {
        arrayCursos = controladorCursos.getArrayCursos();
    }
    
    //Devuelve el ArrayList de Cursos
    public ArrayList <Curso> getArrayCursos()
    {
        setArrayCursos();
        return arrayCursos;
    }
    
    /**
     * Métodos del Frame
     * Estos métodos interactúan con lo que se muestra 
     * (ej: Llenar campos vacíos)
     */
    
    /**
     * Devuelve el String escrito en todos los campos
     * @return the Cursos information String
     */
    public String[] getInformacionEscrita()
    {
        return this.GUI_InformacionCursos.getInformacionEscrita();
    }
    
    /**
     * Devuelve el String en el campo de Siglas
     * @return the siglas
     */
    public String getSiglasEscritas()
    {
        return this.GUI_InformacionCursos.getSiglasEscritas();
    }
    
    //Pide al panel llenar los campos (con la información buscada)
    public void fillFields(String siglas, String nombre, int creditos)
    {
        GUI_InformacionCursos.fillFields(siglas, nombre, creditos);
    }
    
    //Pide al panel limpiar todos los campos
    public void clearFields()
    {
        GUI_InformacionCursos.clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUI_InformacionCursos = new Vista.GUI_InformacionCursos();
        GUI_BotonesCursos = new Vista.GUI_BotonesCursos();

        setTitle("Mantenimiento de Cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUI_BotonesCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GUI_InformacionCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI_InformacionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GUI_BotonesCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesCursos GUI_BotonesCursos;
    private Vista.GUI_InformacionCursos GUI_InformacionCursos;
    // End of variables declaration//GEN-END:variables
}