/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;

/**
 *
 * @author daniel
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame 
{
    Controlador_FRM_MantenimientoCursos controladorCursos;
    
    /**
     * Creates new form FRM_MantenimientoCursos
     */
    public FRM_MantenimientoCursos() 
    {
        initComponents();
        setVisible(false);
        setResizable(false);
        controladorCursos = new Controlador_FRM_MantenimientoCursos(this);
        GUI_BotonesCursos.agregarEventosGUI(controladorCursos);
        GUI_InformacionCursos.agregarEventosGUI(controladorCursos);
    }
    
    
    
    public String[] getInformacionEscrita()
    {
        return this.GUI_InformacionCursos.getInformacionEscrita();
    }
    
    public String getSiglasEscritas()
    {
        return this.GUI_InformacionCursos.getSiglasEscritas();
    }
    
    public void fillFields(String siglas, String nombre, int creditos)
    {
        GUI_InformacionCursos.fillFields(siglas, nombre, creditos);
    }
    
    public void clearFields()
    {
        GUI_InformacionCursos.clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUI_InformacionCursos = new Vista.GUI_InformacionCursos();
        GUI_BotonesCursos = new Vista.GUI_BotonesCursos();

        setTitle("Mantenimiento de Cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUI_BotonesCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GUI_InformacionCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI_InformacionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GUI_BotonesCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesCursos GUI_BotonesCursos;
    private Vista.GUI_InformacionCursos GUI_InformacionCursos;
    // End of variables declaration//GEN-END:variables
}
