
package Vista;

import Controlador.Controlador_FRM_Matriculas;

/**
 * Panel de Búsqueda para Matrícula
 * @author Daniel Somarribas - b57072
 */
public class GUI_BuscarPanelMatriculas extends javax.swing.JPanel {

    /**
     * Creates new form EstudiantesMatriculaPanel
     */
    public GUI_BuscarPanelMatriculas() {
        initComponents();
    }
    
    public void agregarEventosGUI(Controlador_FRM_Matriculas controlador)
    {
        this.jb_BuscarEstudiantes.addActionListener(controlador);
        this.jb_BuscarCursos.addActionListener(controlador);
        this.jb_LimpiarEstudiante.addActionListener(controlador);
        this.jb_LimpiarCurso.addActionListener(controlador);
    }
    
    public String getCedulaEscrita()
    {
        String cedula = this.jtf_Cedula.getText();
        
        return cedula;
    }
    
    public String getSiglasEscritas()
    {
        String siglas;
        
        siglas = jtf_Siglas.getText();
        
        return siglas;
    }
    
    public void fillFieldsEstudiantes(String cedula, String nombre, String direccion)
    {
        this.jtf_Cedula.setText(cedula);
        this.jtf_NombreEstudiante.setText(nombre);
        this.jtf_Direccion.setText(direccion);
    }
    
    public void fillFieldsCursos(String siglas, String nombre, int creditos)
    {
        String creditosStr = ""+creditos;
        
        this.jtf_Siglas.setText(siglas);
        this.jtf_NombreCurso.setText(nombre);
        this.jtf_Creditos.setText(creditosStr);
    }
    
    public void clearFieldsEstudiantes()
    {
        this.jtf_Cedula.setText("");
        this.jtf_NombreEstudiante.setText("");
        this.jtf_Direccion.setText("");
    }

    public void clearFieldsCursos()
    {
        this.jtf_Siglas.setText("");
        this.jtf_NombreCurso.setText("");
        this.jtf_Creditos.setText("");    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_Direccion = new javax.swing.JTextField();
        jtf_NombreEstudiante = new javax.swing.JTextField();
        jtf_Cedula = new javax.swing.JTextField();
        jb_BuscarEstudiantes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_Creditos = new javax.swing.JTextField();
        jtf_Siglas = new javax.swing.JTextField();
        jtf_NombreCurso = new javax.swing.JTextField();
        jb_BuscarCursos = new javax.swing.JButton();
        jb_LimpiarEstudiante = new javax.swing.JButton();
        jb_LimpiarCurso = new javax.swing.JButton();

        jLabel1.setText("Estudiantes");

        jLabel2.setText("Cédula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Dirección");

        jtf_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_DireccionActionPerformed(evt);
            }
        });

        jb_BuscarEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jb_BuscarEstudiantes.setActionCommand("BuscarEstudiantes");

        jLabel5.setText("Cursos");

        jLabel6.setText("Créditos");

        jLabel7.setText("Nombre");

        jLabel8.setText("Siglas");

        jtf_NombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NombreCursoActionPerformed(evt);
            }
        });

        jb_BuscarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jb_BuscarCursos.setActionCommand("BuscarCursos");

        jb_LimpiarEstudiante.setText("Limpiar");
        jb_LimpiarEstudiante.setActionCommand("LimpiarEstudiante");

        jb_LimpiarCurso.setText("Limpiar");
        jb_LimpiarCurso.setActionCommand("LimpiarCurso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_LimpiarEstudiante)
                                    .addComponent(jtf_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_BuscarEstudiantes))
                            .addComponent(jtf_Direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_NombreEstudiante, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jb_LimpiarCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_BuscarCursos))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtf_NombreCurso))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtf_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_LimpiarEstudiante, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jb_LimpiarCurso)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jtf_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtf_NombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jtf_NombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_BuscarCursos)
                                    .addComponent(jb_BuscarEstudiantes))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtf_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_DireccionActionPerformed

    private void jtf_NombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NombreCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jb_BuscarCursos;
    private javax.swing.JButton jb_BuscarEstudiantes;
    private javax.swing.JButton jb_LimpiarCurso;
    private javax.swing.JButton jb_LimpiarEstudiante;
    private javax.swing.JTextField jtf_Cedula;
    private javax.swing.JTextField jtf_Creditos;
    private javax.swing.JTextField jtf_Direccion;
    private javax.swing.JTextField jtf_NombreCurso;
    private javax.swing.JTextField jtf_NombreEstudiante;
    private javax.swing.JTextField jtf_Siglas;
    // End of variables declaration//GEN-END:variables
}
