/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;

/**
 *
 * @author estudiante
 */
public class GUI_InformacionEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionEstudiante
     */
    Controlador_FRM_MantenimientoEstudiantes controlador;
    
    public GUI_InformacionEstudiante() {
        initComponents();
        configInic();
    }
    
    public void configInic()
    {
        jtf_Direccion.setEnabled(false);
        jtf_Nombre.setEnabled(false);
    }
    
    public void configEnab()
    {       
        jtf_Direccion.setEnabled(true);
        jtf_Nombre.setEnabled(true);
    }
    
    public void agregarEventosGUI(Controlador_FRM_MantenimientoEstudiantes controlador)
    {
        this.controlador = controlador;
        this.jb_Buscar.addActionListener(controlador);
    }

    public String[] getInformacionEscrita()
    {
        String arreglo[];
        arreglo = new String[3];
        
        arreglo[0] = this.jtf_Cedula.getText();
        arreglo[1] = this.jtf_Nombre.getText();
        arreglo[2] = this.jtf_Direccion.getText();
        
        return arreglo;
    }
    
    public String getCedulaEscrita()
    {
        String cedula = this.jtf_Cedula.getText();
        
        return cedula;
    }
    
    public void fillFields(String cedula, String nombre, String direccion)
    {
        this.jtf_Cedula.setText(cedula);
        this.jtf_Nombre.setText(nombre);
        this.jtf_Direccion.setText(direccion);
    }
    
    public void clearFields()
    {
        this.jtf_Cedula.setText("");
        this.jtf_Nombre.setText("");
        this.jtf_Direccion.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jtf_Direccion = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_Cedula = new javax.swing.JTextField();
        jb_Buscar = new javax.swing.JButton();

        jl_Cedula.setText("Cédula");

        jl_Nombre.setText("Nombre");

        jl_Direccion.setText("Dirección");

        jtf_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_CedulaKeyPressed(evt);
            }
        });

        jb_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jb_Buscar.setActionCommand("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Direccion)
                            .addComponent(jl_Nombre))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Cedula)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_Cedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Buscar))
                    .addComponent(jtf_Direccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_Buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Cedula))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Direccion)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_CedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_CedulaKeyPressed
        if(evt.getKeyCode() == 10)
        {
            controlador.buscar();
        }
    }//GEN-LAST:event_jtf_CedulaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jtf_Cedula;
    private javax.swing.JTextField jtf_Direccion;
    private javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
