/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;

/**
 *
 * @author daniel
 */
public class GUI_BotonesCursos extends javax.swing.JPanel {

    Controlador_FRM_MantenimientoCursos controlador;
    
    /**
     * Creates new form GUI_BotonesCursos
     */
    public GUI_BotonesCursos() {
        initComponents();
    }

    public void agregarEventosGUI(Controlador_FRM_MantenimientoCursos controlador)
    {
        this.controlador = controlador;
        this.jb_AgregarCurso.addActionListener(controlador);
        this.jb_Buscar.addActionListener(controlador);
        this.jb_MostrarTodos.addActionListener(controlador);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_AgregarCurso = new javax.swing.JButton();
        jb_MostrarTodos = new javax.swing.JButton();
        jb_Buscar = new javax.swing.JButton();

        jb_AgregarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AgregarCurso.png"))); // NOI18N
        jb_AgregarCurso.setActionCommand("Agregar");

        jb_MostrarTodos.setText("Mostrar Todos");
        jb_MostrarTodos.setActionCommand("Todos");
        jb_MostrarTodos.setPreferredSize(new java.awt.Dimension(113, 44));

        jb_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jb_Buscar.setActionCommand("Buscar");
        jb_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_AgregarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_MostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_MostrarTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_AgregarCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_Buscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_AgregarCurso;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_MostrarTodos;
    // End of variables declaration//GEN-END:variables
}
